#!/opt/elasticbeanstalk/lib/ruby/bin/ruby
# frozen_string_literal: true

require 'time'
require 'json'

ec2_metadata = `ec2-metadata --instance-id --public-ipv4`.scan(/^([a-z0-9_-]+): (.*)$/i).to_h
launch_time = File.mtime('/opt/elasticbeanstalk/.aws-eb-system-bootstrapped').utc
eb_env = `/opt/elasticbeanstalk/bin/get-config container --key 'environment_name'`
deploy_env = ENV['DEPLOY_ENV']

if File.exist?('/opt/elasticbeanstalk/deployment/app_version_manifest.json')
  app_version = JSON.parse(File.read('/opt/elasticbeanstalk/deployment/app_version_manifest.json'))
  deployment_id = app_version['DeploymentId']
end

if File.exist?('/var/app/current/.build/build-info.txt')
  build_info = File.read('/var/app/current/.build/build-info.txt').scan(/^([a-z0-9_-]+): (.*)$/i).to_h
  build_time = Time.parse(build_info['Time']).utc
  build_str = <<~EOT
    Build: #{deployment_id} / #{build_time} / #{build_info['User']}
    Commit: #{build_info['Branch']} / #{build_info['Commit']} / #{build_info['Message']}
  EOT
end

msg = <<~EOT

###  WARNING: UNAUTHORIZED ACCESS TO THIS SYSTEM IS PROHIBITED  ###
###  All activities on this system are logged and monitored     ###

Instance: #{ec2_metadata['instance-id']}
Launch time: #{launch_time}
Public IPv4: #{ec2_metadata['public-ipv4']}
EB environment: #{eb_env}
Deploy environment: #{deploy_env}
#{build_str}
EOT

puts msg
